IMAP_SERVER = "imap.gmail.com"
EMAIL_ADDRESS = "EMAIL_ADDRESS"
EMAIL_PASSWORD = "EMAIL_PASSWORD"

BOT_EMAIL_ADDRESS = "BOT_EMAIL_ADDRESS"

BYBIT_API_KEY = "BYBIT_API_KEY"
BYBIT_API_SECRET = "BYBIT_API_SECRET"

KRAKEN_API_KEY = "KRAKEN_API_KEY"
KRAKEN_PRIVETE_KEY = "KRAKEN_PRIVETE_KEY"

BINANCE_API_KEY = "BINANCE_API_KEY"
BINANCE_API_SECRET = "BINANCE_API_SECRET"

IB_HOST = 'IB_HOST'
IB_PORT = 'IB_PORT'
IB_CLIENT_ID = 1
